services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:42069
    depends_on:
      - backend
      
  backend:
    build: ./backend
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "42069"]
    ports:
      - "42069:42069"
    volumes:
      - ./backend/app:/code/app
      - ./static:/code/static
    environment:
      - DATABASE_URL=${MONGO_DATABASE_URL}
      - QDRANT_URL=${QDRANT_URL}
      #Actual path for storing images
      - IMAGES_DIR=/code/static/images
      #Path that will be sent to the client
      - IMAGES_URL_PATH=/static/images
      - STATIC_ROOT=/code/static
      - ENCODER_MODEL=google/siglip-base-patch16-224

      - ALLOWED_ORIGINS=http://localhost:5173
    depends_on:
      - mongo
      - qdrant

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    #ports:
      #- "56290:27017" -- dont expose mongo port at all
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

      MONGO_INITDB_DATABASE: ${MONGO_APP_DB}
      MONGO_INITDB_USERNAME: ${MONGO_APP_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_APP_PASSWORD}
    restart: always
    volumes:
      - mongodata:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrantdata:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"

  qdrant-seeder:
    build:
      context: ./seeder
    depends_on:
      - qdrant
      - mongo
    environment:
      - RUN_SEEDER=false
      - DATABASE_URL=${MONGO_DATABASE_URL}
      - QDRANT_URL=${QDRANT_URL}
      - IMAGES_URL_PATH=/static/images #To mimic client path when actually inserted by the db

volumes:
  mongodata:
  qdrantdata: