services:
  backend:
    build: ./backend
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/code/app
    environment:
      - DATABASE_URL=${MONGO_DATABASE_URL}
      - QDRANT_URL=${QDRANT_URL}
    depends_on:
      - mongo
      - qdrant

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: always
    volumes:
      - mongodata:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrantdata:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"

volumes:
  mongodata:
  qdrantdata: