services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    command: ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:42069"]
    volumes:
      - ./static:/code/static
    environment:
      - DATABASE_URL=${MONGO_DATABASE_URL}
      - QDRANT_URL=http://qdrant:6333
      - IMAGES_DIR=/code/static/images
      - IMAGES_URL_PATH=/static/images
      - STATIC_ROOT=/code/static
      - ENCODER_MODEL=google/siglip-base-patch16-224
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

    depends_on:
      - mongo
      - qdrant

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_APP_DB}
      MONGO_INITDB_USERNAME: ${MONGO_APP_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_APP_PASSWORD}
    restart: always
    volumes:
      - mongodata:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrantdata:/qdrant/storage
    restart: always

  qdrant-seeder:
    build:
      context: ./seeder
    depends_on:
      - qdrant
      - mongo
    environment:
      - RUN_SEEDER=false
      - DATABASE_URL=${MONGO_DATABASE_URL}
      - QDRANT_URL=http://qdrant:6333
      - IMAGES_URL_PATH=/static/images

volumes:
  mongodata:
  qdrantdata: